# Generated by Django 5.2.3 on 2025-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_auto_detected_language_user_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auto_detected_language",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="language_detection_method",
        ),
        migrations.RemoveField(
            model_name="user",
            name="usage_location",
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                help_text="User's manually chosen language preference (e.g., pt-BR, en-US)",
                max_length=10,
                null=True,
            ),
        ),
    ]
