# Generated by Django 5.2.3 on 2025-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has admin privileges",
            ),
        ),
    ]
