# Generated by Django 5.2.3 on 2025-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_detected_language",
            field=models.CharField(
                blank=True,
                help_text="Language automatically detected from Microsoft AD",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country from Microsoft AD",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language_detection_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to detect language (e.g., country, preferredLanguage)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                help_text="Auto-detected or manually set language preference (e.g., pt-BR, en-US)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="usage_location",
            field=models.CharField(
                blank=True,
                help_text="Usage location from Microsoft AD",
                max_length=10,
                null=True,
            ),
        ),
    ]
