# Generated by Django 5.2.3 on 2025-08-22 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("response_text", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "created_at"],
                        name="rag_ragquer_provide_66daea_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="rag_ragquer_success_c6dabc_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="rag_ragquer_user_id_c9930d_idx",
                    ),
                ],
            },
        ),
    ]
