# Generated by Django 5.2.3 on 2025-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatfeedback",
            name="feedback_type",
        ),
        migrations.AddField(
            model_name="chatfeedback",
            name="rating",
            field=models.CharField(
                choices=[("positive", "Positivo"), ("negative", "Negativo")],
                default="positive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatfeedback",
            name="search_query_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatfeedback",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comentário opcional sobre o feedback"
            ),
        ),
    ]
