# Generated by Django 5.2.3 on 2025-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_chatfeedback_feedback_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="audio_duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="chat_audio/"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="content_type",
            field=models.CharField(
                choices=[("text", "Texto"), ("audio", "Áudio")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="transcription",
            field=models.TextField(blank=True),
        ),
    ]
