# Generated by Django 5.2.3 on 2025-09-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_link_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="agent_type",
            field=models.CharField(
                choices=[("knight", "Knight"), ("wizard", "Wizard"), ("bard", "Bard")],
                default="knight",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_handoff",
            field=models.BooleanField(default=False),
        ),
    ]
