# Generated by Django 5.2.3 on 2025-08-04 18:34

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_access_count"),
    ]

    operations = [
        # Rename existing embedding field to embedding_json
        migrations.RenameField(
            model_name="documentchunk",
            old_name="embedding",
            new_name="embedding_json",
        ),
        # Add new vector field
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
