# Generated by Django 5.2.3 on 2025-08-07 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Código de cor hex para UI (#FFFFFF)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Nome do ícone para UI", max_length=50
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição (menor valor aparece primeiro)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria de Recurso",
                "verbose_name_plural": "Categorias de Recursos",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DownloadableDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título do documento", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do documento e como deve ser usado",
                    ),
                ),
                (
                    "ai_guidance",
                    models.TextField(
                        blank=True,
                        help_text="Orientações para a IA sobre quando disponibilizar este documento",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Categoria do documento (RH, Financeiro, Vendas, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo do documento", upload_to="downloadable_docs/"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nome original do arquivo", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Tamanho do arquivo em bytes"),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="Tipo do arquivo (pdf, docx, xlsx, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o documento está ativo para download",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Número de vezes que foi baixado"
                    ),
                ),
                (
                    "share_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de vezes que foi compartilhado pela IA",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para facilitar busca e organização",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Se requer aprovação antes do download"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de expiração do documento",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="knowledge_r_categor_9ff8a7_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="knowledge_r_is_acti_d4e251_idx"
                    ),
                    models.Index(
                        fields=["file_type"], name="knowledge_r_file_ty_b1e192_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("link", "Link Útil"), ("document", "Documento")],
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.IntegerField(help_text="ID do link ou documento"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("shared", "Compartilhado pela IA"),
                            ("clicked", "Clicado pelo usuário"),
                            ("downloaded", "Baixado pelo usuário"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "chat_session_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID da sessão de chat relacionada",
                        null=True,
                    ),
                ),
                (
                    "query_context",
                    models.TextField(
                        blank=True, help_text="Contexto da pergunta que levou à ação"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="knowledge_r_resourc_0f1edf_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="knowledge_r_user_id_a7f361_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="knowledge_r_created_39a6ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título descritivo do link", max_length=255
                    ),
                ),
                ("url", models.URLField(help_text="URL do link")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do conteúdo do link para os colaboradores",
                    ),
                ),
                (
                    "ai_guidance",
                    models.TextField(
                        blank=True,
                        help_text="Orientações para a IA sobre quando compartilhar este link",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Categoria do link (RH, TI, Compliance, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o link está ativo para ser compartilhado",
                    ),
                ),
                (
                    "send_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de vezes que o link foi enviado pela IA",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para facilitar busca e organização",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="knowledge_r_categor_c06a13_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="knowledge_r_is_acti_a4ab5d_idx"
                    ),
                ],
            },
        ),
    ]
