# Generated by Django 5.2.3 on 2025-08-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_audio_duration_chatmessage_audio_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_title", models.CharField(max_length=255)),
                ("link_url", models.URLField()),
                ("link_id", models.IntegerField(blank=True, null=True)),
                (
                    "request_context",
                    models.TextField(
                        blank=True,
                        help_text="Contexto da pergunta que levou ao envio do link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviado"),
                            ("clicked", "Clicado"),
                            ("not_relevant", "Não Relevante"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confiança da IA na relevância do link (0-1)",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Útil"),
                            ("not_helpful", "Não Útil"),
                            ("irrelevant", "Irrelevante"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_requests",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_requests",
                        to="chat.chatsession",
                    ),
                ),
            ],
        ),
    ]
