# Generated by Django 5.2.3 on 2025-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatmessage_agent_type_chatmessage_is_handoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="downloadable_documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="useful_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
