# Generated by Django 5.2.3 on 2025-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="access_count",
            field=models.IntegerField(
                default=0,
                help_text="Número de vezes que o documento foi acessado no RAG",
            ),
        ),
    ]
