# Generated by Django 5.2.3 on 2025-06-24 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("embedding_model", models.CharField(max_length=100)),
                ("dimension", models.IntegerField()),
                ("index_path", models.CharField(max_length=500)),
                ("chunk_size", models.IntegerField(default=700)),
                ("chunk_overlap", models.IntegerField(default=100)),
                ("documents_count", models.IntegerField(default=0)),
                ("vectors_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RagMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_queries", models.IntegerField(default=0)),
                ("successful_queries", models.IntegerField(default=0)),
                ("failed_queries", models.IntegerField(default=0)),
                ("avg_search_duration_ms", models.FloatField(blank=True, null=True)),
                ("avg_embedding_duration_ms", models.FloatField(blank=True, null=True)),
                ("top_queries", models.JSONField(default=list)),
                ("top_documents", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("query_embedding", models.JSONField(blank=True, null=True)),
                ("search_type", models.CharField(default="hybrid", max_length=20)),
                ("semantic_weight", models.FloatField(default=0.7)),
                ("bm25_weight", models.FloatField(default=0.3)),
                ("top_k", models.IntegerField(default=5)),
                ("results_count", models.IntegerField(default=0)),
                ("results", models.JSONField(default=list)),
                ("search_duration_ms", models.IntegerField(blank=True, null=True)),
                ("embedding_duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("semantic_score", models.FloatField(blank=True, null=True)),
                ("bm25_score", models.FloatField(blank=True, null=True)),
                ("combined_score", models.FloatField()),
                ("content", models.TextField()),
                ("rank", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_results",
                        to="rag.searchquery",
                    ),
                ),
            ],
            options={
                "ordering": ["query", "rank"],
            },
        ),
    ]
