"""Add language context agent_type to chat_sessions

Revision ID: 06ce3804d11f
Revises: 2b9d0a675140
Create Date: 2025-09-18 01:26:18.473107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ce3804d11f'
down_revision: Union[str, Sequence[str], None] = '2b9d0a675140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('chat_sessions', sa.Column('agent_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'agent_type')
    op.drop_column('chat_sessions', 'language')
    op.drop_column('chat_sessions', 'context')
    # ### end Alembic commands ###
