"""add_composite_indexes_and_constraints_to_chat_messages

Revision ID: 1c5507fb4e03
Revises: ebab6f474ba3
Create Date: 2025-10-08 12:28:38.334942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5507fb4e03'
down_revision: Union[str, Sequence[str], None] = 'ebab6f474ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_session_message_type', 'chat_messages', ['session_id', 'message_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_session_message_type', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    # ### end Alembic commands ###
