"""Add category_id FK to useful_links and downloadable_documents

Revision ID: 79b476df49a4
Revises: create_admin_emails
Create Date: 2025-09-24 04:28:01.808832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b476df49a4'
down_revision: Union[str, Sequence[str], None] = 'create_admin_emails'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add category_id columns and foreign keys
    op.add_column('downloadable_documents', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('downloadable_documents', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('ix_downloadable_docs_category_id', 'downloadable_documents', ['category_id'], unique=False)
    op.create_foreign_key(op.f('fk_downloadable_documents_category_id_resource_categories'), 'downloadable_documents', 'resource_categories', ['category_id'], ['id'], ondelete='SET NULL')

    op.add_column('useful_links', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('useful_links', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('ix_useful_links_category_id', 'useful_links', ['category_id'], unique=False)
    op.create_foreign_key(op.f('fk_useful_links_category_id_resource_categories'), 'useful_links', 'resource_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove category_id columns and foreign keys
    op.drop_constraint(op.f('fk_useful_links_category_id_resource_categories'), 'useful_links', type_='foreignkey')
    op.drop_index('ix_useful_links_category_id', table_name='useful_links')
    op.alter_column('useful_links', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('useful_links', 'category_id')

    op.drop_constraint(op.f('fk_downloadable_documents_category_id_resource_categories'), 'downloadable_documents', type_='foreignkey')
    op.drop_index('ix_downloadable_docs_category_id', table_name='downloadable_documents')
    op.alter_column('downloadable_documents', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('downloadable_documents', 'category_id')
    # ### end Alembic commands ###
