"""Add message_metadata column to chat messages

Revision ID: b162ecb20b72
Revises: 06ce3804d11f
Create Date: 2025-09-18 22:30:48.981427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b162ecb20b72'
down_revision: Union[str, Sequence[str], None] = '06ce3804d11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'message_metadata')
    # ### end Alembic commands ###
