"""add_refresh_token_rotation_and_device_fingerprinting_fixed

Revision ID: ebab6f474ba3
Revises: 309711da867b
Create Date: 2025-10-06 04:37:12.111813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab6f474ba3'
down_revision: Union[str, Sequence[str], None] = '309711da867b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_admin_emails_email'), 'admin_emails', type_='unique')
    op.create_index(op.f('ix_admin_emails_id'), 'admin_emails', ['id'], unique=False)
    op.create_index(op.f('ix_rag_query_logs_id'), 'rag_query_logs', ['id'], unique=False)
    op.add_column('user_sessions', sa.Column('refresh_token_family', sa.String(length=36), nullable=True))
    op.add_column('user_sessions', sa.Column('device_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_count', sa.Integer(), nullable=True))
    op.add_column('user_sessions', sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_sessions_device_fingerprint'), 'user_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_family'), 'user_sessions', ['refresh_token_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_family'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_fingerprint'), table_name='user_sessions')
    op.drop_column('user_sessions', 'refresh_expires_at')
    op.drop_column('user_sessions', 'last_refresh_at')
    op.drop_column('user_sessions', 'refresh_count')
    op.drop_column('user_sessions', 'device_fingerprint')
    op.drop_column('user_sessions', 'refresh_token_family')
    op.drop_index(op.f('ix_rag_query_logs_id'), table_name='rag_query_logs')
    op.drop_index(op.f('ix_admin_emails_id'), table_name='admin_emails')
    op.create_unique_constraint(op.f('uq_admin_emails_email'), 'admin_emails', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
