"""
Secure Secret Generation Script
Generates secure random secrets for production use
"""
import secrets
import os
import logging
from pathlib import Path
from typing import Dict, Optional

logger = logging.getLogger(__name__)

def generate_secure_key(length: int = 64) -> str:
    """
    Generate a secure random key

    Args:
        length: Length of the key in bytes (default 64)

    Returns:
        URL-safe base64 encoded key
    """
    return secrets.token_urlsafe(length)

def generate_jwt_secret(length: int = 64) -> str:
    """
    Generate a secure JWT secret key

    Args:
        length: Length of the secret in bytes

    Returns:
        Secure JWT secret
    """
    return secrets.token_urlsafe(length)

def generate_csrf_secret(length: int = 32) -> str:
    """
    Generate a secure CSRF token secret

    Args:
        length: Length of the secret in bytes

    Returns:
        Secure CSRF secret
    """
    return secrets.token_urlsafe(length)

def read_existing_env() -> Dict[str, str]:
    """
    Read existing .env file and return as dictionary

    Returns:
        Dictionary of existing environment variables
    """
    env_vars = {}
    env_path = Path(__file__).parent.parent.parent / ".env"

    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()

    return env_vars

def is_insecure_key(key: str) -> bool:
    """
    Check if a key is insecure (default or too short)

    Args:
        key: The key to check

    Returns:
        True if key is insecure
    """
    if not key:
        return True

    # Check for insecure default values
    insecure_defaults = [
        'dev-secret-key-change-in-production',
        'dev-jwt-secret-key-change-in-production',
        'fastapi-insecure-change-me-in-production',
        'your-secret-key-here',
        'your-jwt-secret-key-here',
        'change-me',
        'changeme',
        'default',
        'secret',
        'password',
        'key'
    ]

    # Check if key matches insecure defaults
    if any(default in key.lower() for default in insecure_defaults):
        return True

    # Check minimum length (32 characters for security)
    if len(key) < 32:
        return True

    return False

def generate_env_file(force_regenerate: bool = False) -> None:
    """
    Generate or update .env file with secure secrets

    Args:
        force_regenerate: Force regeneration of all secrets
    """
    env_path = Path(__file__).parent.parent.parent / ".env"
    existing_vars = read_existing_env()

    # Required secrets with their generators
    required_secrets = {
        'SECRET_KEY': generate_secure_key,
        'JWT_SECRET_KEY': generate_jwt_secret,
        'CSRF_SECRET_KEY': generate_csrf_secret,
    }

    updated = False

    for secret_name, generator_func in required_secrets.items():
        existing_value = existing_vars.get(secret_name, '')

        # Check if we need to generate/update this secret
        should_generate = (
            force_regenerate or
            not existing_value or
            is_insecure_key(existing_value)
        )

        if should_generate:
            new_value = generator_func()
            existing_vars[secret_name] = new_value
            updated = True
            logger.info(f"Generated new {secret_name}")
        else:
            logger.info(f"Keeping existing {secret_name}")

    if updated or not env_path.exists():
        # Write updated .env file
        with open(env_path, 'w', encoding='utf-8') as f:
            # Write header comment
            f.write("# Knight Agent Environment Configuration\n")
            f.write("# Generated secrets - DO NOT COMMIT TO VERSION CONTROL\n")
            f.write("# Generated by app/core/generate_secrets.py\n\n")

            # Write secrets first
            f.write("# Security Secrets\n")
            for secret_name in required_secrets.keys():
                if secret_name in existing_vars:
                    f.write(f"{secret_name}={existing_vars[secret_name]}\n")
            f.write("\n")

            # Write other existing variables
            f.write("# Other Configuration\n")
            for key, value in existing_vars.items():
                if key not in required_secrets:
                    f.write(f"{key}={value}\n")

        logger.info(f"✅ Updated .env file at {env_path}")

        # Set restrictive permissions on .env file (Unix only)
        try:
            os.chmod(env_path, 0o600)  # Read/write for owner only
            logger.info("✅ Set secure permissions on .env file")
        except (OSError, AttributeError):
            logger.warning("Could not set permissions on .env file (Windows or permission error)")
    else:
        logger.info("✅ All secrets are already secure, no changes needed")

def validate_current_secrets() -> Dict[str, bool]:
    """
    Validate current secrets in environment

    Returns:
        Dictionary with validation results for each secret
    """
    from app.core.config import settings

    validation_results = {}

    # Check SECRET_KEY
    validation_results['SECRET_KEY'] = not is_insecure_key(settings.SECRET_KEY)

    # Check JWT_SECRET_KEY
    validation_results['JWT_SECRET_KEY'] = not is_insecure_key(settings.JWT_SECRET_KEY)

    return validation_results

def main():
    """
    Main function to generate secrets
    Can be called from command line
    """
    import argparse

    parser = argparse.ArgumentParser(description='Generate secure secrets for Knight Agent')
    parser.add_argument('--force', action='store_true', help='Force regeneration of all secrets')
    parser.add_argument('--validate', action='store_true', help='Only validate current secrets')

    args = parser.parse_args()

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )

    if args.validate:
        print("\n🔍 Validating current secrets...")
        results = validate_current_secrets()

        all_valid = True
        for secret_name, is_valid in results.items():
            status = "✅ SECURE" if is_valid else "❌ INSECURE"
            print(f"{secret_name}: {status}")
            if not is_valid:
                all_valid = False

        if all_valid:
            print("\n✅ All secrets are secure!")
            return 0
        else:
            print("\n❌ Some secrets are insecure. Run without --validate to fix.")
            return 1
    else:
        print("\n🔐 Generating secure secrets...")
        generate_env_file(force_regenerate=args.force)
        print("✅ Done! Remember to restart your application to load new secrets.")
        return 0

if __name__ == "__main__":
    exit(main())